### ISSUE TITLE
Chaincode attackathon notes

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dev-project/battle-of-galen-erso#4]
- [ ] Installation is a pain. try to get kubectl and helm installed via python packages if possible
    - https://github.com/bitcoin-dev-project/warnet/pull/614
    - https://github.com/bitcoin-dev-project/warnet/pull/610
- [ ] kubectl requires at least an empty directory for ./kube to check for config files even if nothing is there:
    - `FileNotFoundError: [Errno 2] No such file or directory: '/home/murch/.kube/config'`
    - fixed by https://github.com/bitcoin-dev-project/warnet/pull/598 ?
- [ ] document needs to be more clear about local / remote steps if going remote, warnet auth needs to come first
- [ ] kubectl commands like `get pods` may not be reliable because of default namesapce, prefer `warnet status` 
    - or provide guidance on how to set default namespace
    - or `warnet auth` should set default namespace
    - fixed by https://github.com/bitcoin-dev-project/warnet/pull/598 ?
- [ ] snap install of k9s doesnt work (need to install brew)
- [ ] clean up failed scenario containers, especially to make warnet logs easier
    - fixed by https://github.com/bitcoin-dev-project/warnet/pull/612
- [ ] easier way to map nodes by IP to tank name and version
- [ ] add new vulnerabilities to make some things easy
- [ ] for atlanta, lets provide small regtest clusters for people to practice on so they dont need docker locally

**Comment by pinheadmz** [comment]
More notes:

1. snap install of k9s doesnt work (need to install brew)

**Comment by pinheadmz** [comment]
clean up failed scenario containers, especially to make warnet logs easier

**Comment by pinheadmz** [comment]
easier way to map nodes by IP to tank name and version

**Comment by pinheadmz** [comment]
turn off debug logging so log files stay small

**Comment by pinheadmz** [comment]
add new vulnerabilities to make some things easy

**Comment by pinheadmz** [comment]
for atlanta, lets provide small regtest clusters for people to practice on so they dont need docker locally

**Comment by mplsgrant** [comment]
> 4. kubectl commands like get pods may not be reliable because of default namesapce, prefer warnet status
> 
>    * or provide guidance on how to set default namespace
>    * or warnet auth should set default namespace
> 

It looks to that the `create_kubeconfigs` function over in https://github.com/bitcoin-dev-project/warnet/pull/598  that @josibake and I are working on *should* provide a default namespace for those users who perform the `warnet auth` on the kubeconfig file that `create_kubeconfigs` generates. 

You can see the namespace set here: https://github.com/bitcoin-dev-project/warnet/blob/297ded4e4ea638f78605eb88b17ae7a39aec4843/src/warnet/admin.py#L110

**Comment by pinheadmz** [comment]
> You can see the namespace set here:

Ok great. The config file i distributed was directly from digital ocean's web console
